openapi: 3.0.3
info:
  title: Todo API
  description: REST API for multi-user todo application with authentication
  version: 1.0.0
servers:
  - url: https://api.todoapp.com/v1
    description: Production server
  - url: https://staging.todoapp.com/v1
    description: Staging server
  - url: http://localhost:8000
    description: Development server

paths:
  /api/{user_id}/tasks:
    get:
      summary: Get all tasks for a user
      description: Retrieve all tasks associated with the specified user
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user whose tasks to retrieve
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: List of tasks for the user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
      security:
        - jwt_auth: []
      tags:
        - Tasks
    post:
      summary: Create a new task
      description: Create a new task for the specified user
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user creating the task
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreateRequest'
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
      security:
        - jwt_auth: []
      tags:
        - Tasks

  /api/{user_id}/tasks/{id}:
    get:
      summary: Get a specific task
      description: Retrieve a specific task by ID for the specified user
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
            format: uuid
        - name: id
          in: path
          required: true
          description: The ID of the task to retrieve
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Task details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
      security:
        - jwt_auth: []
      tags:
        - Tasks
    put:
      summary: Update a task
      description: Update all fields of a specific task for the specified user
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
            format: uuid
        - name: id
          in: path
          required: true
          description: The ID of the task to update
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdateRequest'
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
      security:
        - jwt_auth: []
      tags:
        - Tasks
    delete:
      summary: Delete a task
      description: Delete a specific task for the specified user
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
            format: uuid
        - name: id
          in: path
          required: true
          description: The ID of the task to delete
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Task deleted successfully
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
      security:
        - jwt_auth: []
      tags:
        - Tasks

  /api/{user_id}/tasks/{id}/complete:
    patch:
      summary: Mark task as complete/incomplete
      description: Toggle the completion status of a specific task for the specified user
      parameters:
        - name: user_id
          in: path
          required: true
          description: The ID of the user
          schema:
            type: string
            format: uuid
        - name: id
          in: path
          required: true
          description: The ID of the task to update
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                is_completed:
                  type: boolean
                  description: The new completion status for the task
              required:
                - is_completed
      responses:
        '200':
          description: Task completion status updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
        '400':
          $ref: '#/components/responses/ValidationError'
        '401':
          $ref: '#/components/responses/UnauthorizedError'
        '403':
          $ref: '#/components/responses/ForbiddenError'
        '404':
          $ref: '#/components/responses/NotFoundError'
      security:
        - jwt_auth: []
      tags:
        - Tasks

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
          format: uuid
          description: Unique identifier for the task
        user_id:
          type: string
          format: uuid
          description: ID of the user who owns this task
        title:
          type: string
          description: Task title
          minLength: 1
          maxLength: 200
        description:
          type: string
          description: Detailed task description
          nullable: true
        is_completed:
          type: boolean
          description: Whether the task is completed
          default: false
        created_at:
          type: string
          format: date-time
          description: When the task was created
        updated_at:
          type: string
          format: date-time
          description: When the task was last updated
        due_date:
          type: string
          format: date-time
          description: Optional deadline for the task
          nullable: true
        priority:
          type: string
          description: Task priority level
          enum: [low, medium, high]
          nullable: true
      required:
        - id
        - user_id
        - title
        - is_completed
        - created_at
        - updated_at

    TaskCreateRequest:
      type: object
      properties:
        title:
          type: string
          description: Task title
          minLength: 1
          maxLength: 200
        description:
          type: string
          description: Detailed task description
        due_date:
          type: string
          format: date-time
          description: Optional deadline for the task
        priority:
          type: string
          description: Task priority level
          enum: [low, medium, high]
      required:
        - title

    TaskUpdateRequest:
      type: object
      properties:
        title:
          type: string
          description: Task title
          minLength: 1
          maxLength: 200
        description:
          type: string
          description: Detailed task description
        due_date:
          type: string
          format: date-time
          description: Optional deadline for the task
        priority:
          type: string
          description: Task priority level
          enum: [low, medium, high]
        is_completed:
          type: boolean
          description: Whether the task is completed
      required:
        - title

    Error:
      type: object
      properties:
        error:
          type: string
          description: Error message
        code:
          type: string
          description: Error code
        details:
          type: object
          description: Additional error details
          nullable: true

  responses:
    ValidationError:
      description: Validation error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    UnauthorizedError:
      description: Unauthorized - JWT token missing or invalid
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    ForbiddenError:
      description: Forbidden - User does not have permission to access this resource
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    NotFoundError:
      description: Resource not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  securitySchemes:
    jwt_auth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token for authentication. The token must be included in the Authorization header as "Bearer {token}". The user_id in the URL must match the user_id in the JWT token.

security:
  - jwt_auth: []